version: "3.9"

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-server
    restart: always
    env_file:
      - .env
    environment:
      BACKEND_STORE_URI: ${BACKEND_STORE_URI}
      ARTIFACT_ROOT: ${ARTIFACT_ROOT}
    command: >
      mlflow server
      --backend-store-uri ${BACKEND_STORE_URI}
      --default-artifact-root ${ARTIFACT_ROOT}
      --host 0.0.0.0
      --port 5000
      --serve-artifacts
      --allowed-hosts mlflow-server,localhost,127.0.0.1
    networks:
      - ml-network

  fraud-api:
    image: ghcr.io/godvilan/real-time-ccfds-with-mlops:latest
    container_name: fraud-api
    restart: always
    env_file:
      - .env
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
    depends_on:
      - mlflow
    networks:
      - ml-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fraud-api
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge